embedding_base_url: "https://utbd-west-us.openai.azure.com"
embedding_api_key: "37febf9965e44c8690be3f97c547ccbe"
embedding_deployment: "text-embedding-3-small"  # Changed from "embedding" to match Azure
embedding_deployment_name: "text-embedding-3-small"
embedding_api_version: "2023-05-15"

chat_base_url: "https://utbd-omodels-new.openai.azure.com"
chat_api_key: "5f8f0f2099ce4ff4930a82b7159f3576"
chat_deployment_name: "o1-mini"
chat_api_version: "2023-05-15"
